//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_patient
    {
        public int cn { get; set; }
        public string papin { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string contact_1 { get; set; }
        public string contact_2 { get; set; }
        public string position { get; set; }
        public string marital_status { get; set; }
        public string gender { get; set; }
        public string birthdate { get; set; }
        public string place_of_birth { get; set; }
        public string type_of_job { get; set; }
        public string employer { get; set; }
        public string passport_no { get; set; }
        public string seamansbook_no { get; set; }
        public byte[] picture { get; set; }
        public string registration_date { get; set; }
        public string remarks { get; set; }
        public string nationality { get; set; }
        public string religion { get; set; }
        public string test_data { get; set; }
        public string father_name { get; set; }
        public string father_occupation { get; set; }
        public string mother_name { get; set; }
        public string no_of_brothers { get; set; }
        public string no_of_sisters { get; set; }
        public string birth_order { get; set; }
        public string spouse_name { get; set; }
        public string spouse_occupation { get; set; }
        public string no_of_children { get; set; }
        public string elementary { get; set; }
        public string highschool { get; set; }
        public string college { get; set; }
        public string course { get; set; }
        public string highest_level_attended { get; set; }
        public string mother_occupation { get; set; }
        public string prev_work_start { get; set; }
        public string prev_work_end { get; set; }
        public string prev_company { get; set; }
        public string prev_position { get; set; }
        public string prev_leave_reason { get; set; }
        public string prev_years { get; set; }
        public string date_last_updated { get; set; }
        public string sirb { get; set; }
        public string designation { get; set; }
    }
}
