//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmsiEntities : DbContext
    {
        public cmsiEntities()
            : base("name=cmsiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<m_patient> m_patient { get; set; }
        public DbSet<pbcatcol> pbcatcols { get; set; }
        public DbSet<pbcatedt> pbcatedts { get; set; }
        public DbSet<pbcatfmt> pbcatfmts { get; set; }
        public DbSet<pbcattbl> pbcattbls { get; set; }
        public DbSet<pbcatvld> pbcatvlds { get; set; }
        public DbSet<r_series_gen> r_series_gen { get; set; }
        public DbSet<t_ancillary> t_ancillary { get; set; }
        public DbSet<t_clinical_chemistry> t_clinical_chemistry { get; set; }
        public DbSet<t_fecalysis> t_fecalysis { get; set; }
        public DbSet<t_hematology> t_hematology { get; set; }
        public DbSet<t_hiv> t_hiv { get; set; }
        public DbSet<t_med_history> t_med_history { get; set; }
        public DbSet<t_med_history2> t_med_history2 { get; set; }
        public DbSet<t_others> t_others { get; set; }
        public DbSet<t_phy_exam> t_phy_exam { get; set; }
        public DbSet<t_psychology> t_psychology { get; set; }
        public DbSet<t_radiology> t_radiology { get; set; }
        public DbSet<t_registration> t_registration { get; set; }
        public DbSet<t_result_main> t_result_main { get; set; }
        public DbSet<t_urinalysis> t_urinalysis { get; set; }
        public DbSet<tbl_employer> tbl_employer { get; set; }
        public DbSet<tbl_visit> tbl_visit { get; set; }
    }
}
