//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcatedt
    {
        public int cn { get; set; }
        public string pbe_name { get; set; }
        public string pbe_edit { get; set; }
        public string pbe_type { get; set; }
        public string pbe_cntr { get; set; }
        public string pbe_seqn { get; set; }
        public string pbe_flag { get; set; }
        public string pbe_work { get; set; }
    }
}
