//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcattbl
    {
        public int cn { get; set; }
        public string pbt_tnam { get; set; }
        public string pbt_tid { get; set; }
        public string pbt_ownr { get; set; }
        public string pbd_fhgt { get; set; }
        public string pbd_fwgt { get; set; }
        public string pbd_fitl { get; set; }
        public string pbd_funl { get; set; }
        public string pbd_fchr { get; set; }
        public string pbd_fptc { get; set; }
        public string pbd_ffce { get; set; }
        public string pbh_fhgt { get; set; }
        public string pbh_fwgt { get; set; }
        public string pbh_fitl { get; set; }
        public string pbh_funl { get; set; }
        public string pbh_fchr { get; set; }
        public string pbh_fptc { get; set; }
        public string pbh_ffce { get; set; }
        public string pbl_fhgt { get; set; }
        public string pbl_fwgt { get; set; }
        public string pbl_fitl { get; set; }
        public string pbl_funl { get; set; }
        public string pbl_fchr { get; set; }
        public string pbl_fptc { get; set; }
        public string pbl_ffce { get; set; }
        public string pbt_cmnt { get; set; }
    }
}
