//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbcatfmt
    {
        public int cn { get; set; }
        public string pbf_name { get; set; }
        public string pbf_frmt { get; set; }
        public string pbf_type { get; set; }
        public string pbf_cntr { get; set; }
    }
}
