//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_series_gen
    {
        public int cn { get; set; }
        public string sgname { get; set; }
        public string sgyr { get; set; }
        public string sgmo { get; set; }
        public string sgseries { get; set; }
    }
}
