//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ancillary
    {
        public int cn { get; set; }
        public string result_id { get; set; }
        public string cxr { get; set; }
        public string ecg { get; set; }
        public string cbc { get; set; }
        public string pregnancy_test { get; set; }
        public string urinalysis { get; set; }
        public string stool_exam { get; set; }
        public string hbsag { get; set; }
        public string hiv { get; set; }
        public string rpr { get; set; }
        public string blood_type { get; set; }
        public string blood_chemistries { get; set; }
        public string psychological_exam { get; set; }
        public string additional_test { get; set; }
        public string remarks { get; set; }
        public string recommendation { get; set; }
        public string additional_test2 { get; set; }
    }
}
