//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_clinical_chemistry
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string fbs { get; set; }
        public string fbs_con { get; set; }
        public string bun { get; set; }
        public string bun_con { get; set; }
        public string creatinine { get; set; }
        public string creatinine_con { get; set; }
        public string cholesterol_susp { get; set; }
        public string cholesterol_susp_con { get; set; }
        public string cholesterol_elev { get; set; }
        public string cholesterol_elev_con { get; set; }
        public string uric_acid { get; set; }
        public string uric_acid_con { get; set; }
        public string sgot { get; set; }
        public string sgot_con { get; set; }
        public string sgpt { get; set; }
        public string sgpt_con { get; set; }
        public string alk_phos { get; set; }
        public string alk_phos_con { get; set; }
        public string vdrl { get; set; }
        public string hbsag { get; set; }
        public string ahbe { get; set; }
        public string hbeag { get; set; }
        public string widal_test { get; set; }
        public string malarial_smear { get; set; }
        public string hiv { get; set; }
        public string hbsag_titer { get; set; }
        public string ahbe_titer { get; set; }
        public string hbeag_titer { get; set; }
        public string plasmodium { get; set; }
        public string repeat_test_id { get; set; }
        public string fbs_high { get; set; }
        public string bun_high { get; set; }
        public string creatinine_high { get; set; }
        public string cholesterol_high { get; set; }
        public string triglycerides_high { get; set; }
        public string uric_acid_high { get; set; }
        public string sgot_high { get; set; }
        public string sgpt_high { get; set; }
        public string alk_high { get; set; }
        public string result_date { get; set; }
    }
}
