//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_fecalysis
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string color { get; set; }
        public string ova_parasite { get; set; }
        public string consistency { get; set; }
        public string red_blood_cells { get; set; }
        public string white_blood_cells { get; set; }
        public string amoeba { get; set; }
        public string others { get; set; }
        public string occult_blood { get; set; }
        public string repeat_test_id { get; set; }
        public string pus_cells { get; set; }
        public string mucus { get; set; }
        public string result_date { get; set; }
        public string color_others { get; set; }
    }
}
