//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_hematology
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string hemoglobin { get; set; }
        public string hematocrit { get; set; }
        public string rbc_count { get; set; }
        public string wbc_count { get; set; }
        public string lymphocytes { get; set; }
        public string segmenters { get; set; }
        public string eosinophils { get; set; }
        public string stab_cells { get; set; }
        public string basophils { get; set; }
        public string monocytes { get; set; }
        public string blood_type { get; set; }
        public string esr { get; set; }
        public string others { get; set; }
        public string repeat_test_id { get; set; }
        public string myelocytes { get; set; }
        public string juveniles { get; set; }
        public string platelet { get; set; }
        public string result_date { get; set; }
    }
}
