//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_hiv
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string rapid { get; set; }
        public string particle_agglutination { get; set; }
        public string eia_cmia_elfa { get; set; }
        public string others_specify { get; set; }
        public string results { get; set; }
    }
}
