//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_med_history
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string head_injury { get; set; }
        public string frequent_headaches { get; set; }
        public string frequent_dizziness { get; set; }
        public string fainting_spells { get; set; }
        public string insomnia { get; set; }
        public string depression { get; set; }
        public string trachoma { get; set; }
        public string deafness { get; set; }
        public string nose_throat_disorder { get; set; }
        public string tuberculosis { get; set; }
        public string other_lung_disorder { get; set; }
        public string high_blood_pressure { get; set; }
        public string heart_disease { get; set; }
        public string rheumatic_fever { get; set; }
        public string diabetes_mellitus { get; set; }
        public string other_endocrine_disorder { get; set; }
        public string cancer_tumor { get; set; }
        public string blood_disorders { get; set; }
        public string stomach_pain { get; set; }
        public string other_abdominal_disorder { get; set; }
        public string kidney_bladder_disorder { get; set; }
        public string back_injury { get; set; }
        public string genetic_hereditary { get; set; }
        public string sexually_transmit_disease { get; set; }
        public string tropical_disease { get; set; }
        public string asthma { get; set; }
        public string allergies { get; set; }
        public string gynecological_disorder { get; set; }
        public string operations { get; set; }
        public string operations_specify { get; set; }
        public string others { get; set; }
        public string consulted { get; set; }
        public string consulted_specify { get; set; }
        public string maintenance_meds { get; set; }
        public string operations_tag { get; set; }
        public string schistosomiasis { get; set; }
        public string last_menstrual_period { get; set; }
        public string allergies_specify { get; set; }
        public string other_abdominal_specify { get; set; }
    }
}
