//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_others
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public Nullable<int> SKIN_TAG { get; set; }
        public string SKIN { get; set; }
        public Nullable<int> HEAD_NECK_SCALP_TAG { get; set; }
        public string HEAD_NECK_SCALP { get; set; }
        public Nullable<int> EYES_TAG { get; set; }
        public string EYES { get; set; }
        public Nullable<int> PUPILS_TAG { get; set; }
        public string PUPILS { get; set; }
        public Nullable<int> EARS_EARDRUM_TAG { get; set; }
        public string EARS_EARDRUM { get; set; }
        public Nullable<int> NOSE_SINUSES_TAG { get; set; }
        public string NOSE_SINUSES { get; set; }
        public Nullable<int> MOUTH_THROAT_TAG { get; set; }
        public string MOUTH_THROAT { get; set; }
        public Nullable<int> NECK_LN_THYROID_TAG { get; set; }
        public string NECK_LN_THYROID { get; set; }
        public Nullable<int> CHEST_BREAST_AXILLA_TAG { get; set; }
        public string CHEST_BREAST_AXILLA { get; set; }
        public Nullable<int> LUNGS_TAG { get; set; }
        public string LUNGS { get; set; }
        public Nullable<int> HEART_TAG { get; set; }
        public string HEART { get; set; }
        public Nullable<int> ABDOMEN_TAG { get; set; }
        public string ABDOMEN { get; set; }
        public Nullable<int> BACK_FLANK_TAG { get; set; }
        public string BACK_FLANK { get; set; }
        public Nullable<int> ANUS_RECTUM_TAG { get; set; }
        public string ANUS_RECTUM { get; set; }
        public Nullable<int> GU_SYSTEM_TAG { get; set; }
        public string GU_SYSTEM { get; set; }
        public Nullable<int> INGUINALS_GENITALS_TAG { get; set; }
        public string INGUINALS_GENITALS { get; set; }
        public Nullable<int> REFLEXES_TAG { get; set; }
        public string REFLEXES { get; set; }
        public Nullable<int> EXTREMITIES_TAG { get; set; }
        public string EXTREMITIES { get; set; }
        public string DENTAL { get; set; }
        public Nullable<int> DENTAL_TAG { get; set; }
    }
}
