//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_phy_exam
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string HEIGHT { get; set; }
        public string WEIGHT { get; set; }
        public string BP { get; set; }
        public string PULSE { get; set; }
        public string RESPIRATION { get; set; }
        public string BODY_BUILD { get; set; }
        public string FAR_OD_U { get; set; }
        public string FAR_OD_C { get; set; }
        public string FAR_OS_U { get; set; }
        public string FAR_OS_C { get; set; }
        public string NEAR_ODJ_U { get; set; }
        public string NEAR_ODJ_C { get; set; }
        public string NEAR_OSJ_U { get; set; }
        public string NEAR_OSJ_C { get; set; }
        public string ISHIHARA_U { get; set; }
        public string ISHIHARA_C { get; set; }
        public string HEARING_AD { get; set; }
        public string HEARING_AS { get; set; }
        public string SPEECH { get; set; }
        public string CONVERSATIONAL_AD { get; set; }
        public string CONVERSATIONAL_AS { get; set; }
        public string SATISFACTORY_HEARING { get; set; }
        public string SATISFACTORY_SIGHT_AID { get; set; }
        public string SATISFACTORY_SIGHT_UNAID { get; set; }
        public string SATISFACTORY_PSYCHO { get; set; }
        public string VISUAL_AIDS { get; set; }
        public string FIT_FOR_LOOKOUT { get; set; }
        public string HEARING_RIGHT { get; set; }
        public string HEARING_LEFT { get; set; }
        public string CLARITY_OF_SPEECH { get; set; }
        public string VISUAL_AIDS_REQUIRED { get; set; }
        public string BP_DIASTOLIC { get; set; }
        public string RHYTHM { get; set; }
        public string VISUAL_AIDS_WORN { get; set; }
        public string COLOR_VISION_DATE_TAKEN { get; set; }
        public string UNAIDED_HEARING_SATISFACTORY { get; set; }
        public string IDENTITY_CONFIRMED { get; set; }
    }
}
