//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_psychology
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string type_of_test { get; set; }
        public string intelectual_level { get; set; }
        public string res_persevering { get; set; }
        public string res_obedient { get; set; }
        public string res_selfdiscipline { get; set; }
        public string res_enthusiastic { get; set; }
        public string res_venturesome { get; set; }
        public string emo_isolation_boredom { get; set; }
        public string emo_noise_vibration_temp { get; set; }
        public string emo_reality { get; set; }
        public string emo_confident { get; set; }
        public string emo_stress { get; set; }
        public string emo_relaxed { get; set; }
        public string obj_realistic { get; set; }
        public string obj_jealousy { get; set; }
        public string obj_adaptable { get; set; }
        public string obj_practicalminded { get; set; }
        public string mot_assertive { get; set; }
        public string mot_independent { get; set; }
        public string mot_resourceful { get; set; }
        public string type_of_test_desc { get; set; }
        public string goal_orientation { get; set; }
        public string recommendation { get; set; }
        public string rec_reservation_desc { get; set; }
        public string rec_not_rec_desc { get; set; }
        public string iapa_rel_peer { get; set; }
        public string iapa_rel_superior { get; set; }
        public string iapa_self_esteem { get; set; }
        public string iapa_aggressive_tendencies { get; set; }
        public string intel_test { get; set; }
        public string intel_result { get; set; }
        public string person_test { get; set; }
        public string person_result { get; set; }
        public string other_test { get; set; }
        public string other_result { get; set; }
        public string ff_eval_details { get; set; }
        public string not_rec_details { get; set; }
    }
}
