//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_radiology
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string result_date { get; set; }
        public string papin { get; set; }
        public string reference_no { get; set; }
        public string findings { get; set; }
        public string radiologist { get; set; }
        public string rad_license { get; set; }
        public string examination { get; set; }
        public string impression { get; set; }
    }
}
