//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_registration
    {
        public int cn { get; set; }
        public string trkid { get; set; }
        public string papin { get; set; }
        public string pxtype { get; set; }
        public string trans_date { get; set; }
        public string diagnosis { get; set; }
        public string purpose { get; set; }
    }
}
