//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centerport.Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_urinalysis
    {
        public int cn { get; set; }
        public string resultid { get; set; }
        public string color { get; set; }
        public string transparency { get; set; }
        public string reaction { get; set; }
        public string specific_gravity { get; set; }
        public string sugar { get; set; }
        public string albumin { get; set; }
        public string blood { get; set; }
        public string fine_granular { get; set; }
        public string coarse_granular { get; set; }
        public string hyaline { get; set; }
        public string waxy { get; set; }
        public string rbc { get; set; }
        public string pus { get; set; }
        public string mixed { get; set; }
        public string red_blood_cells { get; set; }
        public string white_blood_cells { get; set; }
        public string calcium_oxalate { get; set; }
        public string uric_acid { get; set; }
        public string triple_phosphate { get; set; }
        public string others_crystals { get; set; }
        public string amorphous_urates { get; set; }
        public string amorphous_phosphates { get; set; }
        public string epithelial_cells { get; set; }
        public string renal_cells { get; set; }
        public string bacteria { get; set; }
        public string mucus_threads { get; set; }
        public string color_remarks { get; set; }
        public string others_specified { get; set; }
        public string repeat_test_id { get; set; }
        public string urine_bile { get; set; }
        public string others_chem { get; set; }
        public string leukocytes { get; set; }
        public string yeast_cells { get; set; }
        public string squamous { get; set; }
        public string result_date { get; set; }
        public string nitrite { get; set; }
        public string urobilinogen { get; set; }
        public string protein { get; set; }
        public string ph { get; set; }
        public string ketone { get; set; }
        public string bilirubin { get; set; }
        public string microscopic_others { get; set; }
        public string cast_others { get; set; }
    }
}
