namespace Centerport
{
    partial class frm_searchTumor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            this.label1 = new System.Windows.Forms.Label();
            this.cmd_clear = new System.Windows.Forms.Button();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.txt_search = new System.Windows.Forms.TextBox();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.label3 = new System.Windows.Forms.Label();
            this.cmd_cancel = new System.Windows.Forms.Button();
            this.cmd_search = new System.Windows.Forms.Button();
            this.cbo_filter = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.patientInformationToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.dg_result = new System.Windows.Forms.DataGridView();
            this.cn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Pap_pin = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ResultId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Column2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Column3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.contextMenuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dg_result)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.ForeColor = System.Drawing.Color.Maroon;
            this.label1.Location = new System.Drawing.Point(3, 286);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(210, 13);
            this.label1.TabIndex = 64;
            this.label1.Text = "Note: Not necessarily to enter the full name";
            // 
            // cmd_clear
            // 
            this.cmd_clear.Font = new System.Drawing.Font("Arial", 9F);
            this.cmd_clear.Location = new System.Drawing.Point(515, 28);
            this.cmd_clear.Name = "cmd_clear";
            this.cmd_clear.Size = new System.Drawing.Size(92, 24);
            this.cmd_clear.TabIndex = 62;
            this.cmd_clear.Text = "Clear";
            this.cmd_clear.UseVisualStyleBackColor = true;
            this.cmd_clear.Click += new System.EventHandler(this.cmd_clear_Click);
            // 
            // txt_search
            // 
            this.txt_search.AutoCompleteCustomSource.AddRange(new string[] {
            "AA",
            "ABAD",
            "ABALLA",
            "ABANDO",
            "ABARCA",
            "ABEJUELA",
            "ABELARDO",
            "ABELLA",
            "ABELLAR",
            "ABELLO",
            "ABESAMIS",
            "ABIDAY",
            "ABILLAR",
            "ABLANIDA",
            "ABLERO",
            "ABORCA",
            "ABOY",
            "ABRIGONDA",
            "ABROT",
            "ABU",
            "ABUAN",
            "ABUBAKAR",
            "ABUNDO",
            "ABURIDO",
            "ACLAN",
            "ACOSTA",
            "ACUÑA",
            "ADANO",
            "ADRIANO",
            "ADVINCULA",
            "AGBANLOG",
            "AGCAOILI",
            "AGDEPPA",
            "AGRUPIS",
            "AGSAO",
            "AGUILAR",
            "AGUILING",
            "AGUILLON",
            "AGUINALDO",
            "AGUIRRE",
            "AGUIT",
            "AGULTO",
            "AGUSTIN",
            "AISPORNA",
            "ALABA",
            "ALABOT",
            "ALBARECE",
            "ALCANTARA",
            "ALCORIZA",
            "ALDEGUER",
            "ALE",
            "ALEJANDRO",
            "ALEJO",
            "ALENTAJE",
            "ALFARO",
            "ALFEREZ",
            "ALFONSO",
            "ALIAS",
            "ALLEGO",
            "ALLON",
            "ALMENIANA",
            "ALMIROL",
            "ALMOSA",
            "ALOJADO",
            "ALOJIPAN",
            "ALONZO",
            "ALVA",
            "ALVARAN",
            "ALVAREZ",
            "ALVIZ",
            "AMABA",
            "AMAN",
            "AMBA",
            "AMBOJIA",
            "AMBOY",
            "AMI",
            "AMISTAD",
            "AMOG",
            "AMOYAN",
            "AMPARO",
            "AMPIT",
            "AMUSING",
            "ANACTA",
            "ANAQUE",
            "ANASTACIO",
            "ANCENO",
            "ANCHETA",
            "ANCIRO",
            "ANDAL",
            "ANDAYA",
            "ANDES",
            "ANDO",
            "ANDRES",
            "ANDRION",
            "ANGCAO",
            "ANGELES",
            "ANGULO",
            "ANICO",
            "AÑONUEVO",
            "ANSELMO",
            "ANTONINO",
            "ANTONIO",
            "APLAON",
            "APODERADO",
            "APOSTOL",
            "AQUINO",
            "ARAGDON ",
            "ARANDELA",
            "ARANIEGO",
            "ARAOLA",
            "ARBOLEDA",
            "ARCENIAS",
            "ARCIGA",
            "ARCIPE",
            "ARCONADO",
            "ARDIENTE",
            "ARELLANO",
            "ARENAS",
            "AREVALO",
            "ARGENAL",
            "ARGUELLES",
            "ARIMADO",
            "ARIOLA",
            "ARLANZA",
            "ARNAIZ",
            "ARQUIOLA",
            "ARTATES",
            "ARTIAGA",
            "ARTUS",
            "ARUCAN",
            "ASADON",
            "ASAÑA",
            "ASESOR",
            "ASTILLAZO",
            "ASUNCION",
            "ATAMOSA",
            "ATANACIO",
            "ATAYDE",
            "ATIENZA",
            "ATRAJE",
            "AURELLANA",
            "AUSTRIA",
            "AVENIDA",
            "AVILA",
            "AVILLANOZA",
            "AY-AY",
            "AZCUETA",
            "AZUCENA",
            "BABAC",
            "BABOL",
            "BACAY",
            "BACLIG",
            "BACNAT",
            "BACOLTO",
            "BACONG",
            "BACUADO",
            "BAESA",
            "BAGARINAO",
            "BAGOS",
            "BAGUIO",
            "BAJA",
            "BAJUM",
            "BAL",
            "BAL-OT",
            "BALABA",
            "BALAIROS",
            "BALAJADIA",
            "BALATBAT",
            "BALBACAL",
            "BALBARINO",
            "BALBASTRO",
            "BALBIN",
            "BALDEDARA",
            "BALDEMOR",
            "BALIDIO",
            "BALINGIT",
            "BALISI",
            "BALITAAN",
            "BALKIN",
            "BALLENTOS",
            "BALLOS",
            "BALMORES",
            "BALTAZAR",
            "BALUNATSE",
            "BALUYUT",
            "BANCOLO",
            "BANCUAL",
            "BANDAGOSA",
            "BANES",
            "BANILAR",
            "BANQUE",
            "BANTA",
            "BANTILES",
            "BANTOG",
            "BANZON",
            "BAQUIRAN",
            "BARANDINO",
            "BARAOIDAN",
            "BARCELLANO",
            "BARGO",
            "BARIMBAO",
            "BARLAM",
            "BARLIS",
            "BARQUILLA",
            "BARREDO",
            "BARRIOS",
            "BARRO",
            "BARROCA",
            "BARROGA",
            "BARTOLOME",
            "BASA",
            "BASAÑES",
            "BASAYSAY",
            "BASCO",
            "BASILIO",
            "BASINAL",
            "BATAC",
            "BATONGBACAL",
            "BATUIGAS",
            "BATUNGBAKAL",
            "BATUTAY",
            "BAUL",
            "BAUSA",
            "BAUTISTA",
            "BAUTRO",
            "BAYBAY",
            "BAYLON",
            "BAYRANTE",
            "BEDONIA",
            "BEDREJO",
            "BEGINO",
            "BEJER",
            "BELEN",
            "BELEY",
            "BELGADO",
            "BELLEZA",
            "BELLO",
            "BELMES",
            "BELZA",
            "BENAMER",
            "BENEDICTO",
            "BENITEZ",
            "BENITO JR.",
            "BERDIN",
            "BERDONAR",
            "BEREBER",
            "BERGADO",
            "BERGANTING",
            "BERJA",
            "BERMAS",
            "BERMUDEZ",
            "BERNABE",
            "BERNALES",
            "BERNARDINO",
            "BERNARDO",
            "BERONDO",
            "BEROSIL",
            "BERTULDO",
            "BESAÑEZ",
            "BESARIO",
            "BESAS",
            "BIGLANG-AWA",
            "BILAS",
            "BILBAO",
            "BILOG",
            "BIÑAS",
            "BINUYA",
            "BIROSEL",
            "BISENIO",
            "BISNAR",
            "BITONG",
            "BLAM",
            "BLAS",
            "BOAYES",
            "BOCALA",
            "BOCBOC",
            "BOCO",
            "BOCTOT",
            "BODEGAS",
            "BODONAL",
            "BOHOLST",
            "BOLANTE",
            "BOLIVAR",
            "BOMBITA",
            "BONDOC",
            "BORBANO",
            "BORJA",
            "BOSQUE",
            "BOTE",
            "BRAVO",
            "BREEDING",
            "BRIBON",
            "BRILLO",
            "BRIN",
            "BRIÑOSA",
            "BRIONES",
            "BROWN ",
            "BUAN",
            "BUEN",
            "BUENAVENTURA",
            "BUENAVIDEZ",
            "BUENCAMINO",
            "BUHAT",
            "BULANADI",
            "BULAONG",
            "BUMATAY",
            "BUNAG",
            "BUNCALAN",
            "BUNDALIAN",
            "BUÑING",
            "BURAYAG",
            "BURLAYAN",
            "BUSOY",
            "BUSUEGO",
            "BUTIAL",
            "CABACCANG",
            "CABALES",
            "CABALHIN",
            "CABALLES",
            "CABALLO",
            "CABANADA",
            "CABANATAN",
            "CABARDO",
            "CABARUBIAS",
            "CABASAG",
            "CABASAL",
            "CABIG",
            "CABRADILLA",
            "CABRAL",
            "CABRERA",
            "CABUG",
            "CABUHAT",
            "CABUNTOG",
            "CABUS",
            "CAC",
            "CACHO",
            "CADA",
            "CADAY",
            "CAGUIA",
            "CAHIGOS",
            "CAHILIG",
            "CAINTIC",
            "CAJAYON",
            "CAJELO",
            "CAJUCOM",
            "CALANSINGIN",
            "CALARA",
            "CALAYAG",
            "CALBAY",
            "CALDEO",
            "CALIMAG",
            "CALISON",
            "CALITIS",
            "CALIWAG",
            "CALLO",
            "CALMA",
            "CALUBAG",
            "CALUPITAN",
            "CAMORAHAN",
            "CAMU",
            "CANABA",
            "CANASA",
            "CANDELARIA",
            "CAÑERO",
            "CANILLO",
            "CANIMO",
            "CANLAS",
            "CANO",
            "CANON",
            "CANOSA",
            "CANOZA",
            "CANSINO",
            "CAO",
            "CAPALAD",
            "CAPINPIN",
            "CAPIRAL",
            "CAPUCHINO",
            "CAPUNDAN",
            "CAPUNO",
            "CARANDANG",
            "CARASCAL",
            "CARBONELL",
            "CARGANDO",
            "CARLOS",
            "CARPIO",
            "CARREON",
            "CASER",
            "CASERIA",
            "CASIMERO",
            "CASIMIRO",
            "CASTAÑARES",
            "CASTILLO",
            "CASTOR",
            "CASTRO",
            "CASTRODES",
            "CASTROVERDE",
            "CASTUERAS",
            "CASUPANAN",
            "CATAHAN",
            "CATINGCO",
            "CAUSON",
            "CAVITANA",
            "CAYA",
            "CAYABYAB",
            "CAYANGA",
            "CAYETANO",
            "CAYRON",
            "CAYSON",
            "CELESTRA",
            "CENTENO",
            "CENTINO",
            "CEPEDA",
            "CERDENIA",
            "CERRO",
            "CERVANTES",
            "CESISTA",
            "CHANLUANGCO",
            "CHAVEZ",
            "CHIAPCO",
            "CHIN",
            "CHUA",
            "CINCO ",
            "CLARAMON",
            "CLARETE",
            "CLAUDIO",
            "CLEMENTE",
            "CLEOPE",
            "CLIMACO",
            "COINCO",
            "COLLADO",
            "COLLERA",
            "COLONIA",
            "COLOQUIO",
            "COMETA",
            "CONANAN",
            "CONCEPCION",
            "CONSERVA",
            "CONSTANTINO",
            "CONTANG ",
            "CORALDE",
            "CORDOVA",
            "CORIO",
            "CORNEJO",
            "CORNEL",
            "CORONEL",
            "CORPIN",
            "CORPUZ",
            "CORREA",
            "CORVERA",
            "CREDO",
            "CRISOLO",
            "CRISOSTOMO",
            "CRISTOBAL",
            "CRUEL",
            "CRUZ",
            "CRUZADO",
            "CUANAN",
            "CUAREZ",
            "CUARTERO",
            "CUBOL",
            "CUEVAS",
            "CUEVO",
            "CULANAG",
            "CULILAP",
            "CUNANAN",
            "CUSILE",
            "CUSTODIO",
            "CUYNO",
            "DABON",
            "DABU",
            "DACARA",
            "DACLAN",
            "DACUDAO",
            "DACUTAN",
            "DAEL",
            "DAGCUTAN",
            "DAGDAGAN",
            "DAGOHOY",
            "DAJAB",
            "DALANGIN",
            "DALAWAMPU",
            "DALING",
            "DALIPE",
            "DALISAY",
            "DAM",
            "DAMEG",
            "DAÑA",
            "DANGANAN",
            "DANTES",
            "DAQUIZ",
            "DARANTINAO",
            "DATINGUINOO",
            "DAVID",
            "DAWAL",
            "DAYAO",
            "DE ARCE",
            "DE BELEN ",
            "DE BOISSIERE",
            "DE CASTRO",
            "DE CHAVEZ",
            "DE GUIA",
            "DE GUZMAN",
            "DE JESUS",
            "DE LA CRUZ",
            "DE LARA",
            "DE LEON",
            "DE LINO",
            "DE LUNA",
            "DE MATEO",
            "DE MESA",
            "DE ROXAS",
            "DE RUEDA",
            "DE SAGON",
            "DE SILVA",
            "DE VERA",
            "DE VILLA",
            "DEDICATORIA",
            "DEGUIA",
            "DEL BARRIO",
            "DEL CARMEN",
            "DEL CASTILLO",
            "DEL POSO",
            "DEL ROSARIO",
            "DEL VALLE",
            "DELA CRUZ",
            "DELA MERCED",
            "DELA PEÑA",
            "DELA ROSA",
            "DELA TORRE",
            "DELACRUZ",
            "DELAROSO",
            "DELGADO",
            "DELLOMES",
            "DELOS AMA",
            "DELOS ANGELES",
            "DELOS REYES",
            "DELOS SANTOS",
            "DELOSO",
            "DEMATE",
            "DEMECAIS",
            "DEMETILLO",
            "DEMETRIO",
            "DEPALOBOS",
            "DERECHO",
            "DERIGE",
            "DESERVA",
            "DIAMANTE",
            "DIANO",
            "DIAZ",
            "DIEGO",
            "DIENTE",
            "DIGNENENG",
            "DIMAAPI",
            "DIMALANTA",
            "DIMAPAWI",
            "DIMAYA",
            "DINGLASAN",
            "DINGSON",
            "DIOLA",
            "DIONISIO",
            "DIRIC",
            "DISCAYA",
            "DIZON",
            "DOGOMEO",
            "DOLOR",
            "DOMANICO",
            "DOMINGO",
            "DOMINGUEZ",
            "DONES",
            "DOPLAYNA",
            "DORADO",
            "DORIA",
            "DOTDOT",
            "DUATIN",
            "DUCO",
            "DUJA",
            "DULA",
            "DULIN",
            "DUMARAN",
            "DUMAYAS",
            "DURAN",
            "DURANA",
            "EBIT",
            "EBREO",
            "EDAÑO",
            "EDOSOR",
            "EGUIA",
            "ELEMENCIO",
            "ELVAMBUENA",
            "EMETERIO",
            "EMPLEO",
            "ENDAYA",
            "ENGLIS",
            "ENIEGO",
            "ENRIQUEZ",
            "ENRIQUEZ III",
            "EREÑA",
            "ERIESO",
            "EROJA",
            "ESCARIO JR.",
            "ESCARLAN",
            "ESCUETA",
            "ESER",
            "ESGUERRA",
            "ESMILLO",
            "ESPAÑOLA",
            "ESPANTO",
            "ESPARAGUERRA",
            "ESPARCIA",
            "ESPELLARGA",
            "ESPINA",
            "ESPINAR",
            "ESPINOSA",
            "ESPIRITU",
            "ESTANISLAO",
            "ESTAVILLO",
            "ESTAYA",
            "ESTEBAN",
            "ESTEVES JR.",
            "ESTIAGA",
            "ESTORNINOS",
            "ESTRADA",
            "ESTRELLA",
            "ETQUIBAL",
            "ETRATA ",
            "EUGENIO",
            "EUSEBIO",
            "EVANGELISTA",
            "FABIAN",
            "FACTOR",
            "FADERA",
            "FADREQUELA",
            "FAELDAN ",
            "FAJARDO",
            "FALGUERA",
            "FALLER",
            "FANDIÑOLA",
            "FAUSTINO",
            "FEGARIDO",
            "FELICES",
            "FELICIANO",
            "FELITRO",
            "FERCOL",
            "FERMIN ",
            "FERNANDEZ",
            "FERNANDO",
            "FERRER",
            "FERRIOL",
            "FIGUEROA",
            "FIRAZA",
            "FLOR",
            "FLORES",
            "FONTANILLA",
            "FORBES",
            "FORTALEZA",
            "FORTUNATO",
            "FORTUS",
            "FRAGO",
            "FRANCIA",
            "FRANCISCO",
            "FRONDA",
            "FRUGALIDAD",
            "FUEDAN",
            "FUENTIVILLA",
            "FUERTES",
            "FULGAR",
            "FULGENCIO",
            "FULGERAS",
            "FULGUERAS",
            "FUNDAN",
            "FUNTALVA",
            "FUNTANARES",
            "FUSIO",
            "GABOT",
            "GABRIEL",
            "GABRINAO",
            "GACOSTA",
            "GADDI",
            "GADIA",
            "GAGAJENA",
            "GALABO",
            "GALANG",
            "GALBAN",
            "GALERA",
            "GALICIA",
            "GALUTAN ",
            "GALVADORES",
            "GALVAN",
            "GALVEZ",
            "GAMBOA",
            "GAMBOL",
            "GANELO",
            "GANGE",
            "GARANGANAO",
            "GARCIA",
            "GARGARITANO",
            "GARIANDO",
            "GARROTE",
            "GASPAR",
            "GATCHALIAN",
            "GATCHE",
            "GATDULA",
            "GATMAITAN",
            "GATUZ",
            "GAVIETA",
            "GAVIN",
            "GAYORGOR",
            "GEDALANGA",
            "GELIBERTE",
            "GENER",
            "GENEZ",
            "GENOTIVA",
            "GENTUGAO",
            "GERALDO",
            "GERMAN",
            "GERMINO",
            "GEROLA",
            "GERONCA",
            "GERONIMO",
            "GESULGON",
            "GICANA",
            "GILDO",
            "GIMENO",
            "GINES",
            "GIPOLIO",
            "GIUBAN",
            "GLORIA",
            "GOLOYA",
            "GOMEZ",
            "GONZALES",
            "GONZALEZ",
            "GOZO",
            "GRADO",
            "GREGORIO",
            "GRIJALDO",
            "GROMIA",
            "GROMIO",
            "GUANSING",
            "GUBATON",
            "GUERRERO",
            "GUESE",
            "GUEVARRA",
            "GUILING",
            "GUINTO",
            "GUITIANO",
            "GULTIANO",
            "GUMARANG",
            "GUMSAT",
            "GUNAYON",
            "GUNTANG",
            "GUSILATAR",
            "GUTIERREZ",
            "HADJI ALAWI",
            "HALIPA",
            "HANDOC",
            "HARDER",
            "HEREDERO",
            "HERMOGENES",
            "HERNANDEZ",
            "HERRERA",
            "HICAO",
            "HIJE",
            "HILADO",
            "HILARIO",
            "HINACAY",
            "HINGCO",
            "HIPOLITO",
            "HIWATIG",
            "HOFILEÑA",
            "HOMBRE",
            "HONA",
            "HONORIO",
            "HORTILLAS",
            "HUYONG",
            "IBAÑEZ",
            "IBARDOLAZA",
            "IBUNA",
            "ICO",
            "IDOS",
            "IDUL",
            "IGNACIO",
            "IGOS",
            "ILAGAN",
            "ILETO",
            "INGALLA",
            "INOCENCIO",
            "INSIGNE",
            "INTACTO",
            "INTANO",
            "INTERIA",
            "ISON",
            "JACABA",
            "JACILDO",
            "JACINTO",
            "JALOVA",
            "JAMORA",
            "JAMPIL",
            "JAPITANA",
            "JAPITANA, JR.",
            "JAQUECA",
            "JARAMILLA",
            "JARATA",
            "JARDINAZO",
            "JARME",
            "JAVATE",
            "JAVIER",
            "JAYME",
            "JIMENEZ",
            "JINO-O",
            "JOAQUIN",
            "JONEM",
            "JORDAN",
            "JOSE",
            "JOVER",
            "JUACHON",
            "JUAN",
            "JUGADO",
            "JUGUETA",
            "JULIANO",
            "JULIO",
            "JUMAO-AS",
            "JUNGCO",
            "JUNIA",
            "JURAO",
            "JUSI",
            "KAIBIGAN",
            "KALAW",
            "LABAGUIS",
            "LABAO",
            "LABITIGAN",
            "LACAMBRA",
            "LACANILAO",
            "LACAYANGA",
            "LACBO",
            "LACE",
            "LACHICA",
            "LACSAMANA",
            "LACSINA",
            "LACTUAN",
            "LACUNA",
            "LADORES",
            "LAGAZO",
            "LAGMAN",
            "LAGRISOLA",
            "LAGUDA",
            "LAGUERTA",
            "LAGUIDAO",
            "LAIM",
            "LAJOM",
            "LALIMARMO",
            "LALO",
            "LAMAYO",
            "LAMBERTE",
            "LAMBINICIO",
            "LAMBINISIO",
            "LAMOSTE",
            "LAMUD",
            "LAMUG",
            "LANDICHO",
            "LANO",
            "LANOY",
            "LANSANGAN",
            "LANZUELA",
            "LAO",
            "LARAWAN",
            "LARCIA",
            "LARIOS",
            "LARIOSA",
            "LARRACAS",
            "LAS PIÑAS",
            "LASCO",
            "LASIC",
            "LASTIMOSA",
            "LATOSA",
            "LAUD",
            "LAURENTE",
            "LAURETA",
            "LAVILLA",
            "LAXAMANA",
            "LAYA",
            "LAYOSA",
            "LAYUGAN",
            "LAZARO",
            "LAZARTE",
            "LEABRES",
            "LEAL",
            "LECAROS",
            "LEDESMA",
            "LEGARA",
            "LEGASPI",
            "LELIS",
            "LEONARDO",
            "LEONCIO",
            "LEONOR",
            "LERIOS",
            "LEYNES",
            "LIBUNAO",
            "LIBUTON",
            "LICANDA",
            "LICAYLICAY",
            "LICUDINE",
            "LIGPIT",
            "LIM",
            "LIMBO",
            "LIMIN",
            "LIMSON",
            "LINGA",
            "LINSANGAN",
            "LIPANA",
            "LIPIT",
            "LIRIA",
            "LISING",
            "LIWA",
            "LIWANAG",
            "LIWANAGAN",
            "LLAMADA",
            "LLAMOSO",
            "LLOREN",
            "LO",
            "LO-FERNANDEZ",
            "LO-FERNANDEZ JR.",
            "LOBETANIA",
            "LOBOS",
            "LOCANA",
            "LOGROÑO",
            "LOMBOY",
            "LONGALONG",
            "LONGOS",
            "LONTOC",
            "LONTOK",
            "LOPEZ",
            "LORENZO",
            "LORES",
            "LORICO",
            "LOTERTE",
            "LOTUACO",
            "LOYOLA",
            "LOZADA",
            "LOZANO",
            "LUCAS",
            "LUCIANO",
            "LUCIAPAO",
            "LUCIDO",
            "LUNA",
            "LUNDAG",
            "LUNES",
            "LUSTERIO",
            "LUZ",
            "LUZON",
            "MA",
            "MA. ZETA",
            "MABITASAN",
            "MACABANTAD",
            "MACABULOS",
            "MACADANGDANG",
            "MACALALAD",
            "MACALALAG",
            "MACALINTAL",
            "MACAM",
            "MACAPAGAL",
            "MACARIO",
            "MACARIOLA",
            "MACASIAB",
            "MACASU",
            "MACATANGAY",
            "MACEDA",
            "MACLI-ING",
            "MACNI JR.",
            "MACONO",
            "MADARICO",
            "MADERA",
            "MADRIA",
            "MADRIGAL",
            "MAGALINGg",
            "MAGALONG",
            "MAGALSO",
            "MAGAT",
            "MAGBALOT",
            "MAGBANUA",
            "MAGBOO",
            "MAGCALAS",
            "MAGDAY",
            "MAGLAQUE",
            "MAGLONCIO",
            "MAGNAYE",
            "MAGNO",
            "MAGPALI",
            "MAGPAYO",
            "MAGSAKAY",
            "MAGSINO",
            "MAGSIPOC",
            "MAGTIBAY",
            "MAHINAY",
            "MAKILANG",
            "MALABANAN",
            "MALAGAD",
            "MALANO",
            "MALINAO",
            "MALLARE",
            "MALLARI",
            "MALLORCA",
            "MALONG",
            "MAMANGON",
            "MAMURI",
            "MANAHAN",
            "MAÑALAC",
            "MANALAD",
            "MANALASTAS",
            "MANALILI",
            "MANALO",
            "MANALON",
            "MANALOTO",
            "MANANGGIT ",
            "MANANGHAYA",
            "MANANQUIL",
            "MANAOIS",
            "MANARES",
            "MANAYAO",
            "MANCENIDO",
            "MANDANE",
            "MANDASOC",
            "MANECLANG",
            "MANERO",
            "MANGILA",
            "MANGITNGIT",
            "MANGLANGIT",
            "MANGOBA",
            "MANGUBAT",
            "MANGULABNAN",
            "MAÑIBO",
            "MANIEGO",
            "MANINGAS",
            "MANIO",
            "MANIPIS",
            "MANIQUIS",
            "MANIQUIZ",
            "MANLANGIT",
            "MANLAPAZ",
            "MANOCAN",
            "MANONGSONG",
            "MANUEL",
            "MANULAT",
            "MANZANILLO",
            "MANZON",
            "MAPOY",
            "MAPUTI",
            "MARAMBA",
            "MARAON",
            "MARASIGAN",
            "MARAVILES",
            "MARCELO",
            "MARCHADO",
            "MARCIAL",
            "MARCO",
            "MARCOS",
            "MARFIL",
            "MARIANO",
            "MARIN",
            "MARK",
            "MAROMA",
            "MARQUESES",
            "MARQUEZ",
            "MARTE",
            "MARTIN",
            "MARTINEZ",
            "MARTIRES",
            "MARTIZANO",
            "MASAGNAY",
            "MASANGKAY",
            "MASAYDA",
            "MASCARIÑA",
            "MASCARIÑAS",
            "MASILANG",
            "MATA",
            "MATEO",
            "MATIAS",
            "MATIC",
            "MATRIZ",
            "MATUGAS",
            "MATUGINA",
            "MATUGUINA",
            "MAURICIO",
            "MAXIMO",
            "MAYHAY",
            "MAYOLA",
            "MAYUGBA",
            "MEJARES",
            "MEJIA",
            "MELGAREJO",
            "MELOCOTON",
            "MEMORANDO",
            "MEMPIN",
            "MENDEZ",
            "MENDOZA",
            "MERANO",
            "MERCADO",
            "MERCED",
            "MERCIALES",
            "MESIAS",
            "MIAT",
            "MIGANO",
            "MIGUEL",
            "MINA",
            "MIRABITE",
            "MIRANDA",
            "MIRARAN",
            "MISLOS",
            "MOAÑA",
            "MOISES",
            "MOLATE",
            "MOLATO",
            "MOLINA",
            "MOLLENIDO",
            "MOLO",
            "MONDIA",
            "MONONG",
            "MONSERATE",
            "MONTALBAN",
            "MONTANER",
            "MONTAOS",
            "MONTE",
            "MONTECILLO",
            "MONTEMAYOR",
            "MONTES",
            "MONTIBON",
            "MONTIERRO",
            "MONTILLANA",
            "MONTOYA",
            "MOOG",
            "MORADA",
            "MORADAS",
            "MORALDE",
            "MORALES",
            "MORANCIL",
            "MORCEN",
            "MORDENO",
            "MORE",
            "MORELOS",
            "MORENO",
            "MORTILLA",
            "MOSICO",
            "MOTEO",
            "MOTOL",
            "MULATO",
            "MUÑEZ",
            "MURILLO",
            "MUSNGI",
            "MUTUC",
            "MUYANA",
            "NAALLATAN",
            "NABONG",
            "NACASI",
            "NACIONALES",
            "NAGUIT",
            "NAILAT",
            "NALLOS",
            "NALUZ",
            "NANA",
            "NANQUIL",
            "NAPALLATAN",
            "NAPARAM",
            "NARIDO",
            "NARISMA",
            "NATIVIDAD",
            "NAVAL",
            "NAVARRO",
            "NAZAR",
            "NECOR",
            "NEMENZO",
            "NEPOMUCENO",
            "NERI",
            "NERVAR",
            "NICMIC",
            "NICOLAS",
            "NIDOY",
            "NIETO",
            "NILLOS",
            "NIU",
            "NIZA",
            "NOLASCO",
            "NOLEAL",
            "NOMANANAP",
            "NOVEDA",
            "NUÑEZ",
            "OBAGA",
            "OBANIL",
            "OBAR",
            "OBIEN",
            "OBMERGA",
            "OBRA",
            "OCAMPO",
            "OCATE",
            "OCIONES",
            "OFREN",
            "OFRIN",
            "OGAD",
            "OGALESCO",
            "OGANA",
            "OGAY",
            "OLALIA",
            "OLIVA",
            "OLIVEROS",
            "OLOY",
            "OMERO",
            "ONG",
            "OPAO",
            "OPEÑA",
            "ORACION",
            "ORAIN",
            "ORALLO",
            "ORDINAL",
            "ORDOÑEZ",
            "OREJODOS",
            "OREJUDOS",
            "ORLINA",
            "ORMAS",
            "ORNALES",
            "ORNOPIA",
            "OROCEO",
            "ORPILLA",
            "ORTEGA",
            "ORTEZA",
            "ORTILE",
            "ORTIZ",
            "OSICOS",
            "OSIO",
            "OSITA",
            "PABI",
            "PABILING",
            "PABLEO",
            "PABLO",
            "PACHICA",
            "PACLIBAR",
            "PACSA",
            "PACULBA",
            "PADILLA",
            "PADILLO",
            "PADOLINA",
            "PADUA",
            "PADUL",
            "PAGLINAWAN",
            "PAGTALUNAN",
            "PAGUNSAN",
            "PAJARILLAGA",
            "PAJATE",
            "PAJE",
            "PAJUYO",
            "PALACAY",
            "PALACIO",
            "PALAD",
            "PALAPAG",
            "PALMES",
            "PALOMAR",
            "PALOMARES",
            "PALOMO",
            "PALTAO",
            "PALUBIO",
            "PAMA",
            "PAMINTUAN",
            "PAMPLONA",
            "PANAGSAGAN",
            "PANAGUITON",
            "PANALIGAN",
            "PANARIGAN",
            "PANES",
            "PANGANIBAN",
            "PANGILINAN",
            "PANIQUE",
            "PANIZA",
            "PANOPIO",
            "PANTALEON",
            "PARAISO",
            "PARAL",
            "PARALLAG",
            "PARAON",
            "PARCON",
            "PAREJA",
            "PARTACALAO",
            "PARUNGAO",
            "PASADILLA",
            "PASAMBA",
            "PASANA",
            "PASARON",
            "PASCUA",
            "PASCUAL",
            "PASPE",
            "PASSION",
            "PASTORIL",
            "PASTRANA",
            "PATAM",
            "PATAWARAN",
            "PATEÑA",
            "PATNONGON",
            "PATRICIO",
            "PAULE",
            "PAULINO",
            "PAUNAN",
            "PAYAWAL",
            "PAYNOR",
            "PAYOYO",
            "PAYUMO",
            "PAZ",
            "PAZO",
            "PEDIANGCO",
            "PELAEZ",
            "PELAYO",
            "PEÑA",
            "PEÑAFLOR",
            "PEÑAFLORIDA",
            "PEÑALOSA",
            "PEÑAMAYOR",
            "PEÑASA",
            "PENASO",
            "PENDON",
            "PENIS",
            "PENSON",
            "PEPITO",
            "PERALTA",
            "PEREÑA",
            "PERET",
            "PEREZ",
            "PERIA",
            "PERLAS",
            "PESTAÑO",
            "PIADOZO",
            "PICAR",
            "PILAR",
            "PILI",
            "PILLE",
            "PINEDA",
            "PINGOL",
            "PINGOY",
            "PINLAC",
            "PIRA",
            "PITAHIN",
            "PITPIT",
            "PLACIBE",
            "PLATON",
            "PLAZA",
            "POBRE",
            "POLICARPIO",
            "POLINTAN",
            "POLIQUIT",
            "PONCE",
            "POSTRERO",
            "PRADO",
            "PRECIOSO",
            "PRECLARO",
            "PRESNO",
            "PRINCIPE",
            "PRONUEVO",
            "PUENTESPINA",
            "PUNO",
            "PUNONGBAYAN",
            "PUNSALAN",
            "PUNZALAN",
            "PURINO",
            "PUYAOAN",
            "QUEBILAN",
            "QUEMADO",
            "QUERIJERO",
            "QUERO",
            "QUEZON",
            "QUIAÑO",
            "QUIBILAN",
            "QUILAO",
            "QUILATES",
            "QUILLOPE",
            "QUIMBA",
            "QUIMZON",
            "QUINDOZA",
            "QUINGCO",
            "QUIÑONES",
            "QUINTANA",
            "QUINTERO",
            "QUINTO",
            "QUIPANES",
            "QUIROZ",
            "QUITORIANO",
            "QUITUA",
            "QUIZON",
            "RABANES",
            "RADA",
            "RAFANAN",
            "RAGASA",
            "RAMIREZ",
            "RAMISCAL",
            "RAMOS",
            "RANTE ",
            "RAON",
            "RAPADAS",
            "RARAS",
            "RAVAGO",
            "RAYMUNDO",
            "RAYO",
            "RAZON",
            "REBADAJO",
            "REBUENO",
            "REGALA",
            "REGISTOS",
            "RELAMPAGOS",
            "REMBULAT",
            "RENTEGRADO",
            "REOLA",
            "REOSIA",
            "REPOLLES",
            "RESOL",
            "REVIS",
            "REY",
            "REYES",
            "REYNALDO",
            "RIEGO",
            "RIEZA",
            "RILLERA",
            "RIÑON",
            "RIVERA",
            "RIVERO",
            "ROA",
            "ROBIELOS",
            "ROBLEDO",
            "ROBLES",
            "ROCACORBA",
            "RODEJERO",
            "RODIL",
            "RODRIGO",
            "RODRIGUEZ",
            "RODUTA",
            "ROMANTICO",
            "ROMEO",
            "ROMERO",
            "RONCESVALLES",
            "ROQUE",
            "ROSAL",
            "ROSALES",
            "ROSARY",
            "ROSAS",
            "ROSEL",
            "ROSELLO",
            "ROSETE",
            "ROSQUITES",
            "ROTERSOS",
            "RUBIAS",
            "RUBIN",
            "RUEDA",
            "RUIZ",
            "SABADO",
            "SABALBORO",
            "SABALLA",
            "SABER",
            "SABINO",
            "SACEDOR",
            "SACOPASO",
            "SACULLES",
            "SADIASA",
            "SAGCELO",
            "SAGRADO",
            "SAGUDO",
            "SAGUM",
            "SAGUN",
            "SAITO",
            "SALAC",
            "SALADO",
            "SALALAC",
            "SALANDRON",
            "SALAS",
            "SALAZAR",
            "SALCEDO",
            "SALE",
            "SALES",
            "SALINAS",
            "SALONGA",
            "SALTING",
            "SALTIVAN",
            "SALUTAN",
            "SALUTEM",
            "SALVADOR",
            "SALVATIERRA",
            "SALVINO",
            "SAMANIEGO",
            "SAMONTE",
            "SAMPAYAN",
            "SAMSON",
            "SAMSONA",
            "SAN ANDRES",
            "SAN DIEGO",
            "SAN GABRIEL",
            "SAN JOSE",
            "SAN JUAN",
            "SAN MIGUEL",
            "SAN PEDRO",
            "SANCHEZ",
            "SANDIEGO",
            "SANDOVAL",
            "SANGALANG",
            "SANGELES",
            "SANGIL",
            "SANTALISIS",
            "SANTANDER",
            "SANTIAGO",
            "SANTOS",
            "SAPADEN",
            "SAPALARAN",
            "SAPIO",
            "SARANGAYA",
            "SARMIENTO",
            "SARREAL",
            "SARRONDO",
            "SARSOZA",
            "SARTO",
            "SASAN",
            "SASI",
            "SASIS",
            "SATO",
            "SAWALI",
            "SEBASTIAN",
            "SECRETO",
            "SEDANO",
            "SEDANTES",
            "SEGARRA",
            "SEGUMBAN",
            "SEQUIHOD",
            "SERGANTES",
            "SERPA JUAN",
            "SERRANO",
            "SERVANDE",
            "SERVIANO",
            "SERVIDAD",
            "SERVILLA",
            "SESE",
            "SEVILLA ",
            "SIAPCO",
            "SICAT",
            "SIEGA",
            "SILAN",
            "SILANG",
            "SILVA",
            "SILVANO",
            "SILVELA",
            "SILVERIO",
            "SILVINO",
            "SIMBAJON",
            "SIMBULAN",
            "SIMMONS",
            "SINIPETE",
            "SIOSON",
            "SISTONA",
            "SOAN",
            "SOBREVIÑAS",
            "SOLLANO",
            "SOLOCIO",
            "SOLSONA",
            "SOMODIO",
            "SOMOGAT",
            "SON",
            "SONTILLANO",
            "SONZA",
            "SORIA",
            "SORIAL",
            "SORIANO",
            "SOTELO",
            "SOTO",
            "STA JUANA",
            "STA MARIA",
            "STA. CRUZ",
            "STA. MARIA",
            "STA. RITA",
            "STA.MARIA",
            "SUAREZ",
            "SUBA",
            "SUBANG",
            "SUGUITAN",
            "SULIT",
            "SUMABONG",
            "SUMADIA",
            "SUMANTING",
            "SUMAT",
            "SUMILE",
            "SUÑER",
            "SUNGA",
            "SUPAN",
            "SUPNET",
            "SURATOS",
            "SURIAGA",
            "SURIO",
            "SY",
            "TABANERA",
            "TABARA",
            "TABAYAY",
            "TABERNA",
            "TABLATE",
            "TABORA",
            "TACAZON",
            "TACUD",
            "TADEO",
            "TAGALA",
            "TAGUIAM",
            "TALASTAS",
            "TALAUGON",
            "TALAVERA",
            "TALLO",
            "TALLOD",
            "TALLON",
            "TAMAYO",
            "TAMBIS",
            "TAN",
            "TANALEON",
            "TANCAWAN",
            "TANDOG",
            "TANGALIN",
            "TANGENTE",
            "TAÑOLA",
            "TANTOY",
            "TAPANG",
            "TAPDASAN",
            "TAPIA",
            "TARUC",
            "TATON",
            "TATSON",
            "TAYAO",
            "TAYCO",
            "TAYONE",
            "TECSON",
            "TEGRADO",
            "TEJADA",
            "TEJE",
            "TELEGRAPO",
            "TEMPLADO",
            "TENGCO",
            "TERCIAS",
            "TERMULO",
            "TESALUNA",
            "TIBURCIO",
            "TIEMSIN",
            "TIENZO",
            "TIMAGOS",
            "TIMOTEO",
            "TIRADO",
            "TIROL",
            "TOLEDO",
            "TOLENTINO",
            "TOMAS",
            "TONGCO",
            "TOPE",
            "TORIANO",
            "TORMON",
            "TORRALBA",
            "TORRANO",
            "TORRELIZA",
            "TORRES",
            "TORRILLA",
            "TORTOLES",
            "TRANQUILO",
            "TRECHO",
            "TRESICO",
            "TRIBIANA",
            "TRINIDAD",
            "TRONCO",
            "TUARES",
            "TUBANG",
            "TUBONGBANUA",
            "TUCIO",
            "TUGADE",
            "TUGNAO",
            "TUIZA",
            "TUMAQUE",
            "TUMBOCON",
            "TUMBOKON",
            "TUPAS",
            "TURINGAN",
            "TURLA",
            "TURQUEZA",
            "TUSON",
            "UBEDA",
            "UMALI",
            "UNCIANO JR.",
            "UNTALAN",
            "URBANO",
            "URIARTE",
            "URMANITA",
            "UY",
            "UYCHUTIN",
            "VACAL",
            "VAJIO",
            "VALBUENA",
            "VALCARCEL",
            "VALDERAMA",
            "VALDERIA",
            "VALDEZ",
            "VALDUEZA",
            "VALENCIA",
            "VALENTIN",
            "VALENZONA",
            "VALENZUELA",
            "VALERIANO",
            "VALERIO",
            "VALERO",
            "VALEROSO",
            "VALEZA",
            "VALLE",
            "VALMADRID",
            "VALMEO",
            "VALONDO",
            "VARDELEON",
            "VARGAS",
            "VARILLA",
            "VARON",
            "VARQUEZ",
            "VASQUEZ",
            "VELASCO",
            "VELOSO",
            "VENASQUEZ",
            "VENCI",
            "VENDICACION",
            "VENDIOLA",
            "VENERACION",
            "VENTUCILLO",
            "VENTURA",
            "VENTURINA",
            "VERAYO",
            "VERBO",
            "VERDILLO",
            "VERGARA",
            "VIBAL",
            "VIBAR",
            "VICENTE",
            "VICERAL",
            "VICTORIA",
            "VICTORIANO",
            "VIDAL",
            "VIGUILLA",
            "VILCHEZ",
            "VILLA",
            "VILLACORTA",
            "VILLACORTE",
            "VILLAFANE",
            "VILLAFLOR",
            "VILLAFUERTE",
            "VILLAN",
            "VILLANUEVA",
            "VILLAREAL",
            "VILLAROMAN",
            "VILLARTA",
            "VILLARUBIA",
            "VILLARUEL",
            "VILLAS",
            "VILLASPER",
            "VILLAVICENCIO",
            "VILLEGAS",
            "VILLENA",
            "VILLESIS",
            "VILLONES",
            "VILLOS",
            "VINCO",
            "VINCULADO",
            "VINLUAN",
            "VINUYA",
            "VIRTUDAZO",
            "VISORIO",
            "VISPO",
            "VITE",
            "VIUDEZ",
            "WATIN",
            "YABUT",
            "YAMBAO",
            "YAMBOT",
            "YAMSON ",
            "YANDOC",
            "YANGA",
            "YAP",
            "YARZA",
            "YASAY",
            "YECLA",
            "YGUSQUEZA",
            "YUKIT",
            "YUMANG",
            "ZAFRA",
            "ZAMORA",
            "ZAPATA",
            "ZETA",
            "ZOLETA",
            "ZUÑIGA"});
            this.txt_search.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.txt_search.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txt_search.BackColor = System.Drawing.Color.DarkSeaGreen;
            this.txt_search.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txt_search.Font = new System.Drawing.Font("Arial", 9F);
            this.txt_search.Location = new System.Drawing.Point(203, 30);
            this.txt_search.Name = "txt_search";
            this.txt_search.Size = new System.Drawing.Size(303, 21);
            this.txt_search.TabIndex = 59;
            this.toolTip1.SetToolTip(this.txt_search, "Search by Lastname, Firstname Middle name");
            this.txt_search.TextChanged += new System.EventHandler(this.txt_search_TextChanged);
            this.txt_search.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_search_KeyDown);
            // 
            // timer1
            // 
            this.timer1.Enabled = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.SystemColors.Control;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.SteelBlue;
            this.label3.Location = new System.Drawing.Point(207, 10);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(130, 13);
            this.label3.TabIndex = 63;
            this.label3.Text = "Format  \"Dela Cruz, Juan\"\r\n";
            // 
            // cmd_cancel
            // 
            this.cmd_cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.cmd_cancel.Font = new System.Drawing.Font("Arial", 9F);
            this.cmd_cancel.Location = new System.Drawing.Point(515, 274);
            this.cmd_cancel.Name = "cmd_cancel";
            this.cmd_cancel.Size = new System.Drawing.Size(92, 25);
            this.cmd_cancel.TabIndex = 61;
            this.cmd_cancel.Text = "Cancel";
            this.cmd_cancel.UseVisualStyleBackColor = true;
            // 
            // cmd_search
            // 
            this.cmd_search.Font = new System.Drawing.Font("Arial", 9F);
            this.cmd_search.Location = new System.Drawing.Point(417, 274);
            this.cmd_search.Name = "cmd_search";
            this.cmd_search.Size = new System.Drawing.Size(92, 25);
            this.cmd_search.TabIndex = 60;
            this.cmd_search.Text = "Select";
            this.cmd_search.UseVisualStyleBackColor = true;
            this.cmd_search.Click += new System.EventHandler(this.cmd_search_Click);
            // 
            // cbo_filter
            // 
            this.cbo_filter.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbo_filter.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbo_filter.FormattingEnabled = true;
            this.cbo_filter.Items.AddRange(new object[] {
            "Result ID",
            "Patient Name"});
            this.cbo_filter.Location = new System.Drawing.Point(69, 28);
            this.cbo_filter.Name = "cbo_filter";
            this.cbo_filter.Size = new System.Drawing.Size(128, 23);
            this.cbo_filter.TabIndex = 58;
            this.cbo_filter.SelectedIndexChanged += new System.EventHandler(this.cbo_filter_SelectedIndexChanged);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(16, 32);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(53, 15);
            this.label2.TabIndex = 57;
            this.label2.Text = "Filter By:";
            // 
            // contextMenuStrip1
            // 
            this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.patientInformationToolStripMenuItem});
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new System.Drawing.Size(178, 26);
            // 
            // patientInformationToolStripMenuItem
            // 
            this.patientInformationToolStripMenuItem.Name = "patientInformationToolStripMenuItem";
            this.patientInformationToolStripMenuItem.Size = new System.Drawing.Size(177, 22);
            this.patientInformationToolStripMenuItem.Text = "Patient Information";
            this.patientInformationToolStripMenuItem.Click += new System.EventHandler(this.patientInformationToolStripMenuItem_Click);
            // 
            // dg_result
            // 
            this.dg_result.AllowUserToAddRows = false;
            this.dg_result.AllowUserToDeleteRows = false;
            this.dg_result.AllowUserToResizeColumns = false;
            this.dg_result.AllowUserToResizeRows = false;
            this.dg_result.BackgroundColor = System.Drawing.Color.White;
            this.dg_result.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dg_result.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dg_result.ColumnHeadersHeight = 28;
            this.dg_result.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dg_result.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.cn,
            this.Pap_pin,
            this.ResultId,
            this.Column2,
            this.Column3});
            this.dg_result.ContextMenuStrip = this.contextMenuStrip1;
            this.dg_result.Location = new System.Drawing.Point(4, 57);
            this.dg_result.Name = "dg_result";
            this.dg_result.ReadOnly = true;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DarkSeaGreen;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dg_result.RowHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dg_result.RowHeadersVisible = false;
            this.dg_result.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dg_result.Size = new System.Drawing.Size(602, 212);
            this.dg_result.TabIndex = 65;
            this.dg_result.DoubleClick += new System.EventHandler(this.dg_result_DoubleClick);
            // 
            // cn
            // 
            this.cn.HeaderText = "cn";
            this.cn.Name = "cn";
            this.cn.ReadOnly = true;
            this.cn.Visible = false;
            // 
            // Pap_pin
            // 
            this.Pap_pin.HeaderText = "papin";
            this.Pap_pin.Name = "Pap_pin";
            this.Pap_pin.ReadOnly = true;
            this.Pap_pin.Visible = false;
            // 
            // ResultId
            // 
            this.ResultId.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.DisplayedCells;
            this.ResultId.HeaderText = "Result ID";
            this.ResultId.Name = "ResultId";
            this.ResultId.ReadOnly = true;
            this.ResultId.Width = 76;
            // 
            // Column2
            // 
            this.Column2.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.Column2.HeaderText = "Patient Name";
            this.Column2.Name = "Column2";
            this.Column2.ReadOnly = true;
            // 
            // Column3
            // 
            this.Column3.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.DisplayedCells;
            this.Column3.HeaderText = "Result Date";
            this.Column3.Name = "Column3";
            this.Column3.ReadOnly = true;
            this.Column3.Width = 88;
            // 
            // frm_searchTumor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(611, 309);
            this.ControlBox = false;
            this.Controls.Add(this.dg_result);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.cmd_clear);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.cmd_cancel);
            this.Controls.Add(this.cmd_search);
            this.Controls.Add(this.txt_search);
            this.Controls.Add(this.cbo_filter);
            this.Controls.Add(this.label2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.KeyPreview = true;
            this.Name = "frm_searchTumor";
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Search Patient";
            this.Load += new System.EventHandler(this.frm_searchTumor_Load);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.frm_searchTumor_KeyDown);
            this.contextMenuStrip1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dg_result)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button cmd_clear;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.TextBox txt_search;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button cmd_cancel;
        private System.Windows.Forms.Button cmd_search;
        private System.Windows.Forms.ComboBox cbo_filter;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem patientInformationToolStripMenuItem;
        public System.Windows.Forms.DataGridView dg_result;
        private System.Windows.Forms.DataGridViewTextBoxColumn cn;
        private System.Windows.Forms.DataGridViewTextBoxColumn Pap_pin;
        private System.Windows.Forms.DataGridViewTextBoxColumn ResultId;
        private System.Windows.Forms.DataGridViewTextBoxColumn Column2;
        private System.Windows.Forms.DataGridViewTextBoxColumn Column3;
    }
}